### ISSUE TITLE
Драконы

### ISSUE THREAD

**Issue by kkmarkel** [KTune/prog_markelova#5]
Присылаю [драконов](https://github.com/KTune/prog_markelova/blob/master/Arithmetic_Dragons/GAME.py), пока без троллей(сложна). Попробовала все сюжетные линии, пайчарм не ругался. :)

@antosha417

**Comment by antosha417** [comment]
Тут закрывай, сдавайте вместе с Мишей в его issue. Если не знаешь как делать троллей спроси в чате.
